---
application:
  name: "daisyxmusic"
  project: "Musicbot patrici"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "Musicbot"
routers:
- name: "main-daisyxmusic"
  routes:
  - application_name: "daisyxmusic"
    paths:
    - "/*"
